### ISSUE TITLE
Should there be a way to remove or edit puzzles from the admin page?

### ISSUE THREAD

**Issue by lsammut** [AustralianSynchrotron/openday-scavenger#72] opened 2024-09-18 10:22 UTC
Currently you can add puzzles to the admin page, but there is no way to update/edit details of the puzzle (if you get something wront), or remove it from the admin page (different to disabling it).

**Comment by luigiferiani** [comment] 2024-09-19 01:40
Duplicate of #5

**Closed as not planned** 2024-09-19 01:40 UTC
Labels: duplicate
